function [t,dtdPROP] = t_pureshear(lambda1,in2)
%T_PURESHEAR
%    [T,dtdPROP] = T_PURESHEAR(LAMBDA1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    25-Apr-2025 19:09:08

alpha1 = in2(:,1);
alpha2 = in2(:,3);
alpha3 = in2(:,5);
alpha4 = in2(:,7);
mu1 = in2(:,2);
mu2 = in2(:,4);
mu3 = in2(:,6);
mu4 = in2(:,8);
t2 = log(lambda1);
t3 = lambda1.^alpha1;
t4 = lambda1.^alpha2;
t5 = lambda1.^alpha3;
t6 = lambda1.^alpha4;
t7 = 1.0./lambda1;
t8 = log(t7);
t9 = t7.^alpha1;
t10 = t7.^alpha2;
t11 = t7.^alpha3;
t12 = t7.^alpha4;
t = t7.*(mu1.*t3+mu2.*t4+mu3.*t5-mu1.*t9+mu4.*t6-mu2.*t10-mu3.*t11-mu4.*t12);
if nargout > 1
    dtdPROP = [mu1.*t7.*(t2.*t3-t8.*t9);t7.*(t3-t9);mu2.*t7.*(t2.*t4-t8.*t10);t7.*(t4-t10);mu3.*t7.*(t2.*t5-t8.*t11);t7.*(t5-t11);mu4.*t7.*(t2.*t6-t8.*t12);t7.*(t6-t12)];
end
end
