function [t,dtdPROP] = t_uniaxial(lambda1,in2)
%T_UNIAXIAL
%    [T,dtdPROP] = T_UNIAXIAL(LAMBDA1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    25-Apr-2025 19:09:07

alpha1 = in2(:,1);
alpha2 = in2(:,3);
alpha3 = in2(:,5);
alpha4 = in2(:,7);
mu1 = in2(:,2);
mu2 = in2(:,4);
mu3 = in2(:,6);
mu4 = in2(:,8);
t2 = log(lambda1);
t3 = alpha1-1.0;
t4 = alpha2-1.0;
t5 = alpha3-1.0;
t6 = alpha4-1.0;
t7 = alpha1./2.0;
t8 = alpha2./2.0;
t9 = alpha3./2.0;
t10 = alpha4./2.0;
t11 = lambda1.^t3;
t12 = lambda1.^t4;
t13 = lambda1.^t5;
t14 = lambda1.^t6;
t15 = -t7;
t16 = -t8;
t17 = -t9;
t18 = -t10;
t19 = t15-1.0;
t20 = t16-1.0;
t21 = t17-1.0;
t22 = t18-1.0;
t23 = lambda1.^t19;
t24 = lambda1.^t20;
t25 = lambda1.^t21;
t26 = lambda1.^t22;
t = mu1.*t11+mu2.*t12+mu3.*t13+mu4.*t14-mu1.*t23-mu2.*t24-mu3.*t25-mu4.*t26;
if nargout > 1
    dtdPROP = [(mu1.*t2.*t23.*(lambda1.^(alpha1.*(3.0./2.0)).*2.0+1.0))./2.0;t11-t23;(mu2.*t2.*t24.*(lambda1.^(alpha2.*(3.0./2.0)).*2.0+1.0))./2.0;t12-t24;(mu3.*t2.*t25.*(lambda1.^(alpha3.*(3.0./2.0)).*2.0+1.0))./2.0;t13-t25;(mu4.*t2.*t26.*(lambda1.^(alpha4.*(3.0./2.0)).*2.0+1.0))./2.0;t14-t26];
end
end
