% FiginFig ----------------------------------------------------------------
% Article: Fontes, V.O., Leitão, A.X., & Pereira, A. (2025). 
%          HyperSym: an educational MATLAB code for hyperelasticity
%          Computer Applications in Engineering Education
%          DOI: 10.1002/cae.70037
% -------------------------------------------------------------------------
function FigInFig(ax,vec,x,y,LineColor,LineStyle,MarkerType,MarkerTam)
% Figure inside figure.

set(ax,'Xlim',vec(1,:),'Ylim',vec(2,:));

EdgeColor = LineColor;

hold all; box on

for j = length(x):-1:1
    plot(ax,x{j},y{j},...
        'Color',LineColor{j},...
        'LineStyle',LineStyle{j},...
        'LineWidth',1,...
        'Marker',MarkerType{j},...
        'MarkerSize',MarkerTam{j},...
        'MarkerEdgeColor',EdgeColor{j},...
        'MarkerFaceColor','none')
end

patch('Faces',1:4,...
    'Vertices',[vec(1,1) vec(2,1); vec(1,2) vec(2,1); vec(1,2) vec(2,2); vec(1,1) vec(2,2)],...
    'FaceAlpha',0.1,...
    'EdgeColor','none',...
    'HandleVisibility','off')
end