% ReadAnsysData -----------------------------------------------------------
% Article: Fontes, V.O., Leitão, A.X., & Pereira, A. (2025). 
%          HyperSym: an educational MATLAB code for hyperelasticity
%          Computer Applications in Engineering Education
%          DOI: 10.1002/cae.70037
%-------------------------------------------------------------------------
function Ansys = ReadAnsysData(nn,timestep,lineDisp,lineStress,jump,fileName)
% Read output file generated by Ansys.

i = 0; j = 1; k = 0; l = 1;  % counters

DispID = fopen(fileName{1},'r');

Disp = zeros(nn*(timestep+1),3);

while j <= timestep+1
    item = textscan(DispID,'%*f %*f %f %f %f',nn,...
        'Delimiter','\n','Headerlines',lineDisp);
    Disp(i+1:j*nn,:) = cell2mat(item);
    
    i = i + nn;       j = j + 1;       lineDisp = lineDisp + jump;
    fseek(DispID,0,'bof');
end

fclose(DispID);

% Streches
stretch = 1 + Disp;  

StressID = fopen(fileName{2},'r');

CauchyStress = zeros(nn*(timestep+1),6);
MeanCauchy = zeros(timestep+1,6);

while l <= timestep+1
    item = textscan(StressID,'%*f %*f %f %f %f %f %f %f',nn,...
        'Delimiter','\n','Headerlines',lineStress);
    CauchyStress(k+1:l*nn,:) = cell2mat(item);
    
    % Centroid' Element Stresses at eath time step
    % It can be evaluated as the average nodal values
    % [\tau_11 \tau_22 \tau_33 \tau_12 \tau_23 \tau_13] x timestep
    MeanCauchy(l,:) = mean(CauchyStress(k+nn:l*nn,:),1);
    
    k = k + nn;       l = l + 1;       lineStress = lineStress + jump;
    fseek(StressID,0,'bof');
end

fclose(StressID);

% Output Struct
Ansys = struct(...
    'Disp',Disp,...
    'Stretch',stretch,...
    'CauchyStress',CauchyStress,...
    'Cauchy',MeanCauchy ...
    );
end