function [Sv,Dv] = SVK(in1,in2)
%SVK
%    [Sv,Dv] = SVK(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    19-Dec-2024 11:56:06

C1_1 = in1(1);
C1_2 = in1(4);
C1_3 = in1(7);
C2_2 = in1(5);
C2_3 = in1(8);
C3_3 = in1(9);
lambda = in2(:,1);
mu = in2(:,2);
t2 = C1_1.*2.0;
t3 = C2_2.*2.0;
t4 = C3_3.*2.0;
t5 = mu.*2.0;
t6 = lambda+t5;
t7 = t2+t3+t4-6.0;
t8 = (lambda.*t7)./4.0;
Sv = [t8+(mu.*(t2-2.0))./2.0;t8+(mu.*(t3-2.0))./2.0;t8+(mu.*(t4-2.0))./2.0;C1_2.*mu;C2_3.*mu;C1_3.*mu];
if nargout > 1
    Dv = [t6;lambda;lambda;0.0;0.0;0.0;lambda;t6;lambda;0.0;0.0;0.0;lambda;lambda;t6;0.0;0.0;0.0;0.0;0.0;0.0;mu;0.0;0.0;0.0;0.0;0.0;0.0;mu;0.0;0.0;0.0;0.0;0.0;0.0;mu];
end
end
